global:
  scrape_interval: 1m
  evaluation_interval: 1m

rule_files:
  - rules/*.yml

alerting:
  alertmanagers:
    - static_configs:
      - targets:
        - localhost:9093

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
        - localhost:9090

  - job_name: alertmanager
    static_configs:
      - targets:
        - localhost:9093

  - job_name: node_exporter
    static_configs:
      - targets:
        - localhost:9100

  - job_name: blackbox_exporter
    static_configs:
      - targets:
        - localhost:9115

  - job_name: blackbox_http
    metrics_path: /probe
    params:
      module: [http]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - source_labels: [__param_module]
        target_label: module
      - target_label: __address__
        replacement: localhost:9115
    static_configs:
      - targets:
        - https://dc3.se
