global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
      - targets:
        - dc3.se:9093

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
        - dc3.se:9090

  - job_name: alertmanager
    static_configs:
      - targets:
        - dc3.se:9093

  - job_name: node_exporter
    static_configs:
      - targets:
        - dc3.se:9100
        - dndwiki.dc3.se:9100
