version: "3"

volumes:
  postgresql:
  uploads:

services:
  postgresql:
    image: postgres:16-alpine
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - /var/run/postgres/postgres.sock:/var/run/postgres/postgres.sock
      - postgresql:/var/lib/postgresql/data
    env_file:
      - postgresql.env
    restart: unless-stopped
    
  directus:
    image: directus/directus:10.9.2
    depends_on:
      - postgresql
    ports:
      - 127.0.0.1:8055:8055
    volumes:
      #- /var/lib/directus/database:/directus/database
      - uploads:/directus/uploads
      #- /var/lib/directus/extensions:/directus/extensions
    env_file:
      - directus.env
    restart: unless-stopped
