name: Deploy Web

on:
  push:
    branches:
      - master
    paths:
      - "pb/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: /bin/bash ./.github/scripts/deploy.sh pb
        env:
          DEPLOY_HOST: "${{ secrets.DEPLOY_HOST }}"
          DEPLOY_USER: "${{ secrets.DEPLOY_USER }}"
          PRIVATE_KEY: "${{ secrets.PRIVATE_KEY }}"
