name: Deploy PocketBase

on:
  push:
    branches:
      - master
    paths:
      - "pb/**"
      - ".github/scripts/pb_**"
      - ".github/workflows/pb_**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: /bin/bash ./.github/scripts/pb_deploy.sh
        env:
          DEPLOY_HOST: "${{ secrets.DEPLOY_HOST }}"
          DEPLOY_USER: "${{ secrets.DEPLOY_USER }}"
          PRIVATE_KEY: "${{ secrets.PRIVATE_KEY }}"
