name: Deploy Web

on:
  push:
    branches:
      - master
    paths:
      - "web/**"
      - ".github/scripts/web_**"
      - ".github/workflows/web_**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: /bin/bash ./.github/scripts/web_deploy.sh
        env:
          DEPLOY_HOST: "${{ secrets.DEPLOY_HOST }}"
          DEPLOY_USER: "${{ secrets.DEPLOY_USER }}"
          PRIVATE_KEY: "${{ secrets.PRIVATE_KEY }}"
